#!/bin/sh

set -e

TARGET="${LOGPOITNS_HOME:-"$(dirname "$0")"}"
VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -B)"
LIB="${LIB:-"$TARGET/lib"}"
JAR="${JAR:-"$LIB/logpoints-$VERSION-jar-with-dependencies.jar"}"

java -Dorg.slf4j.simpleLogger.defaultLogLevel=trace -XX:+UseSerialGC -cp "$JAR" anana5.sense.logpoints.PrintGraph "$@"
